import React, { useState, useRef } from 'react';
import { Dream, Language, UserProfile, SubscriptionTier, ThemeMode } from '../types';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import { getTheme } from '../theme';

interface DreamShareProps {
    dream: Dream;
    language: Language;
    userProfile: UserProfile | null;
    onGenerateImage?: (quality: 'normal' | 'high', style: 'cartoon' | 'anime' | 'real' | 'fantasy') => void;
    onGenerateStoryVideo?: (style: 'cartoon' | 'anime' | 'real' | 'fantasy' | 'surreal' | 'watercolor') => void;
    tier?: SubscriptionTier;
    themeMode?: ThemeMode;
}

const translations = {
    [Language.EN]: {
        pdf_not_ready: "PDF template not ready. Please try again.",
        pdf_error: "Error generating PDF. Please try again.",
        generate_image: "🖼️ Image",
        story_video: "📖 Story Video",
        story_desc: "Slideshow + Voice",
        select_style: "Choose Style",
        select_quality: "Choose Quality",
        normal: "Normal",
        premium: "Premium (Gold)",
        cartoon: "Cartoon",
        anime: "Anime",
        real: "Realistic",
        fantasy: "Fantasy",
        surreal: "Surreal",
        watercolor: "Watercolor",
        cartoon_desc: "Pixar/Disney Style",
        anime_desc: "Studio Ghibli",
        real_desc: "Photorealistic",
        fantasy_desc: "Magical & Epic",
        surreal_desc: "Dreamlike & Abstract",
        watercolor_desc: "Artistic Painting",
        back: "Back",
        copy_link: "Link",
        copied: "Copied!",
        share_btn: "Share Text",
        pdf_share_btn: "Share PDF",
        pdf_download_btn: "Download PDF",
        share_error: "Sharing files not supported on this device. Downloading instead.",
        copy_fallback: "Link copied to clipboard.",
        pdf_title: "Select PDF Style",
        style_papyrus: "Papyrus (Light)",
        style_mystic: "Mystic (Dark)",
        style_feminine: "Feminine (Rose)",
        generating: "Generating PDF...",
        success: "Done!",
        web_link: "www.dreammatch.app",
        start_btn: "Create PDF",
        locked: "Silver Tier Required",
        pdf_the_dream: "The Dream",
        pdf_oracle_interpretation: "Oracle Interpretation",
        pdf_oracle_analysis: "Oracle Analysis",
        pdf_generated_by: "Generated by AI • DreamMatch App"
    },
    [Language.DE]: {
        pdf_not_ready: "PDF-Vorlage nicht bereit. Bitte erneut versuchen.",
        pdf_error: "Fehler beim Erstellen des PDFs. Bitte erneut versuchen.",
        generate_image: "🖼️ Bild",
        story_video: "📖 Story Video",
        story_desc: "Slideshow + Stimme",
        select_style: "Stil wählen",
        select_quality: "Qualität wählen",
        normal: "Normal",
        premium: "Premium (Gold)",
        cartoon: "Cartoon",
        anime: "Anime",
        real: "Realistisch",
        fantasy: "Fantasy",
        surreal: "Surreal",
        watercolor: "Aquarell",
        cartoon_desc: "Pixar/Disney Stil",
        anime_desc: "Studio Ghibli",
        real_desc: "Fotorealistisch",
        fantasy_desc: "Magisch & Episch",
        surreal_desc: "Traumhaft & Abstrakt",
        watercolor_desc: "Künstlerisch",
        back: "Zurück",
        copy_link: "Link",
        copied: "Kopiert!",
        share_btn: "Traum teilen",
        pdf_share_btn: "PDF teilen",
        pdf_download_btn: "PDF herunterladen",
        share_error: "Dateien teilen hier nicht unterstützt. Download gestartet.",
        copy_fallback: "Link kopiert.",
        pdf_title: "PDF Stil wählen",
        style_papyrus: "Papyrus (Hell)",
        style_mystic: "Mystic (Dunkel)",
        style_feminine: "Feminin (Rose)",
        generating: "Erstelle PDF...",
        success: "Fertig!",
        web_link: "www.dreammatch.app",
        start_btn: "PDF Erstellen",
        locked: "Silber Status benötigt",
        pdf_the_dream: "Der Traum",
        pdf_oracle_interpretation: "Orakel-Deutung",
        pdf_oracle_analysis: "Orakel-Analyse",
        pdf_generated_by: "Erstellt mit KI • DreamMatch App"
    },
    [Language.TR]: {
        pdf_not_ready: "PDF şablonu hazır değil. Lütfen tekrar deneyin.",
        pdf_error: "PDF oluşturma hatası. Lütfen tekrar deneyin.",
        generate_image: "🖼️ Görsel",
        story_video: "📖 Hikaye Video",
        story_desc: "Slayt + Ses",
        select_style: "Stil Seç",
        select_quality: "Kalite Seç",
        normal: "Normal",
        premium: "Premium (Gold)",
        cartoon: "Çizgi Film",
        anime: "Anime",
        real: "Gerçekçi",
        fantasy: "Fantastik",
        surreal: "Sürreal",
        watercolor: "Sulu Boya",
        cartoon_desc: "Pixar/Disney",
        anime_desc: "Studio Ghibli",
        real_desc: "Foto-gerçekçi",
        fantasy_desc: "Büyülü & Epik",
        surreal_desc: "Rüya Gibi",
        watercolor_desc: "Sanatsal",
        back: "Geri",
        copy_link: "Link",
        copied: "Kopyalandı!",
        share_btn: "Rüyayı Paylaş",
        pdf_share_btn: "PDF Paylaş",
        pdf_download_btn: "PDF İndir",
        share_error: "Dosya paylaşımı desteklenmiyor. İndiriliyor.",
        copy_fallback: "Bağlantı kopyalandı.",
        pdf_title: "PDF Stili Seç",
        style_papyrus: "Papirüs (Aydınlık)",
        style_mystic: "Mistik (Karanlık)",
        style_feminine: "Feminen (Gül)",
        generating: "PDF oluşturuluyor...",
        success: "Tamamlandı!",
        web_link: "www.dreammatch.app",
        start_btn: "PDF Oluştur",
        locked: "Gümüş Üyelik Gerekli",
        pdf_the_dream: "Rüya",
        pdf_oracle_interpretation: "Kahin Yorumu",
        pdf_oracle_analysis: "Kahin Analizi",
        pdf_generated_by: "Yapay Zeka ile oluşturuldu • DreamMatch App"
    },
    [Language.ES]: {
        pdf_not_ready: "Plantilla PDF no lista. Intenta de nuevo.",
        pdf_error: "Error al generar PDF. Intenta de nuevo.",
        generate_image: "🖼️ Imagen",
        story_video: "📖 Video Historia",
        story_desc: "Presentación + Voz",
        select_style: "Elegir Estilo",
        select_quality: "Elegir Calidad",
        normal: "Normal",
        premium: "Premium (Oro)",
        cartoon: "Dibujo",
        anime: "Anime",
        real: "Realista",
        fantasy: "Fantasía",
        surreal: "Surrealista",
        watercolor: "Acuarela",
        cartoon_desc: "Estilo Pixar",
        anime_desc: "Studio Ghibli",
        real_desc: "Fotorrealista",
        fantasy_desc: "Mágico y Épico",
        surreal_desc: "Onírico",
        watercolor_desc: "Artístico",
        back: "Volver",
        copy_link: "Link",
        copied: "¡Copiado!",
        share_btn: "Compartir Sueño",
        pdf_share_btn: "Compartir PDF",
        pdf_download_btn: "Descargar PDF",
        share_error: "Compartir archivos no compatible. Descargando.",
        copy_fallback: "Enlace copiado.",
        pdf_title: "Seleccionar Estilo PDF",
        style_papyrus: "Papiro (Claro)",
        style_mystic: "Místico (Oscuro)",
        style_feminine: "Femenino (Rosa)",
        generating: "Generando PDF...",
        success: "¡Listo!",
        web_link: "www.dreammatch.app",
        start_btn: "Crear PDF",
        locked: "Nivel Plata Requerido",
        pdf_the_dream: "El Sueño",
        pdf_oracle_interpretation: "Interpretación del Oráculo",
        pdf_oracle_analysis: "Análisis del Oráculo",
        pdf_generated_by: "Generado por IA • DreamMatch App"
    },
    [Language.FR]: {
        pdf_not_ready: "Modèle PDF non prêt. Veuillez réessayer.",
        pdf_error: "Erreur lors de la génération du PDF. Veuillez réessayer.",
        generate_image: "🖼️ Image",
        story_video: "📖 Vidéo Histoire",
        story_desc: "Diaporama + Voix",
        select_style: "Choisir Style",
        select_quality: "Choisir Qualité",
        normal: "Normal",
        premium: "Premium (Or)",
        cartoon: "Dessin Animé",
        anime: "Anime",
        real: "Réaliste",
        fantasy: "Fantaisie",
        surreal: "Surréaliste",
        watercolor: "Aquarelle",
        cartoon_desc: "Style Pixar",
        anime_desc: "Studio Ghibli",
        real_desc: "Photoréaliste",
        fantasy_desc: "Magique & Épique",
        surreal_desc: "Onirique",
        watercolor_desc: "Artistique",
        back: "Retour",
        copy_link: "Lien",
        copied: "Copié!",
        share_btn: "Partager le Rêve",
        pdf_share_btn: "Partager PDF",
        pdf_download_btn: "Télécharger PDF",
        share_error: "Partage de fichiers non pris en charge. Téléchargement.",
        copy_fallback: "Lien copié.",
        pdf_title: "Sélectionner le Style PDF",
        style_papyrus: "Papyrus (Clair)",
        style_mystic: "Mystique (Sombre)",
        style_feminine: "Féminin (Rose)",
        generating: "Génération du PDF...",
        success: "Terminé !",
        web_link: "www.dreammatch.app",
        start_btn: "Créer PDF",
        locked: "Niveau Argent Requis",
        pdf_the_dream: "Le Rêve",
        pdf_oracle_interpretation: "Interprétation de l'Oracle",
        pdf_oracle_analysis: "Analyse de l'Oracle",
        pdf_generated_by: "Généré par IA • DreamMatch App"
    },
    [Language.AR]: {
        pdf_not_ready: "قالب PDF غير جاهز. حاول مرة أخرى.",
        pdf_error: "خطأ في إنشاء PDF. حاول مرة أخرى.",
        generate_image: "🖼️ صورة",
        story_video: "📖 فيديو قصة",
        story_desc: "عرض + صوت",
        select_style: "اختر النمط",
        select_quality: "اختر الجودة",
        normal: "عادي",
        premium: "مميز (ذهبي)",
        cartoon: "كرتون",
        anime: "أنمي",
        real: "واقعي",
        fantasy: "خيالي",
        surreal: "سريالي",
        watercolor: "ألوان مائية",
        cartoon_desc: "نمط بيكسار",
        anime_desc: "ستوديو جيبلي",
        real_desc: "صور واقعية",
        fantasy_desc: "سحري وملحمي",
        surreal_desc: "حالم",
        watercolor_desc: "فني",
        back: "رجوع",
        copy_link: "رابط",
        copied: "تم النسخ!",
        share_btn: "مشاركة الحلم",
        pdf_share_btn: "مشاركة PDF",
        pdf_download_btn: "تنزيل PDF",
        share_error: "مشاركة الملفات غير مدعومة. جارٍ التنزيل.",
        copy_fallback: "تم نسخ الرابط.",
        pdf_title: "اختر نمط PDF",
        style_papyrus: "بردي (فاتح)",
        style_mystic: "صوفي (داكن)",
        style_feminine: "أنثوي (وردي)",
        generating: "إنشاء PDF...",
        success: "تم!",
        web_link: "www.dreammatch.app",
        start_btn: "إنشاء PDF",
        locked: "يتطلب المستوى الفضي",
        pdf_the_dream: "الحلم",
        pdf_oracle_interpretation: "تفسير الأوراكل",
        pdf_oracle_analysis: "تحليل الأوراكل",
        pdf_generated_by: "تم الإنشاء بالذكاء الاصطناعي • DreamMatch App"
    },
    [Language.PT]: {
        pdf_not_ready: "Modelo PDF não pronto. Tente novamente.",
        pdf_error: "Erro ao gerar PDF. Tente novamente.",
        generate_image: "🖼️ Imagem",
        story_video: "📖 Vídeo História",
        story_desc: "Apresentação + Voz",
        select_style: "Escolher Estilo",
        select_quality: "Escolher Qualidade",
        normal: "Normal",
        premium: "Premium (Ouro)",
        cartoon: "Desenho",
        anime: "Anime",
        real: "Realista",
        fantasy: "Fantasia",
        surreal: "Surreal",
        watercolor: "Aquarela",
        cartoon_desc: "Estilo Pixar",
        anime_desc: "Studio Ghibli",
        real_desc: "Fotorrealista",
        fantasy_desc: "Mágico e Épico",
        surreal_desc: "Onírico",
        watercolor_desc: "Artístico",
        back: "Voltar",
        copy_link: "Link",
        copied: "Copiado!",
        share_btn: "Compartilhar Sonho",
        pdf_share_btn: "Compartilhar PDF",
        pdf_download_btn: "Baixar PDF",
        share_error: "Compartilhamento não suportado. Baixando.",
        copy_fallback: "Link copiado.",
        pdf_title: "Selecionar Estilo PDF",
        style_papyrus: "Papiro (Claro)",
        style_mystic: "Místico (Escuro)",
        style_feminine: "Feminino (Rosa)",
        generating: "Gerando PDF...",
        success: "Pronto!",
        web_link: "www.dreammatch.app",
        start_btn: "Criar PDF",
        locked: "Nível Prata Necessário",
        pdf_the_dream: "O Sonho",
        pdf_oracle_interpretation: "Interpretação do Oráculo",
        pdf_oracle_analysis: "Análise do Oráculo",
        pdf_generated_by: "Gerado por IA • DreamMatch App"
    },
    [Language.RU]: {
        pdf_not_ready: "Шаблон PDF не готов. Попробуйте ещё раз.",
        pdf_error: "Ошибка создания PDF. Попробуйте ещё раз.",
        generate_image: "🖼️ Картинка",
        story_video: "📖 Видео-История",
        story_desc: "Слайды + Голос",
        select_style: "Выбрать Стиль",
        select_quality: "Выбрать Качество",
        normal: "Обычное",
        premium: "Премиум (Золото)",
        cartoon: "Мультфильм",
        anime: "Аниме",
        real: "Реалистичный",
        fantasy: "Фэнтези",
        surreal: "Сюрреализм",
        watercolor: "Акварель",
        cartoon_desc: "Стиль Pixar",
        anime_desc: "Студия Гибли",
        real_desc: "Фотореализм",
        fantasy_desc: "Магия и Эпика",
        surreal_desc: "Сновидческий",
        watercolor_desc: "Художественный",
        back: "Назад",
        copy_link: "Ссылка",
        copied: "Скопировано!",
        share_btn: "Поделиться Сном",
        pdf_share_btn: "Поделиться PDF",
        pdf_download_btn: "Скачать PDF",
        share_error: "Обмен файлами не поддерживается. Загрузка.",
        copy_fallback: "Ссылка скопирована.",
        pdf_title: "Выберите Стиль PDF",
        style_papyrus: "Папирус (Светлый)",
        style_mystic: "Мистический (Тёмный)",
        style_feminine: "Женственный (Розовый)",
        generating: "Создание PDF...",
        success: "Готово!",
        web_link: "www.dreammatch.app",
        start_btn: "Создать PDF",
        locked: "Требуется Серебряный Уровень",
        pdf_the_dream: "Сон",
        pdf_oracle_interpretation: "Толкование Оракула",
        pdf_oracle_analysis: "Анализ Оракула",
        pdf_generated_by: "Создано ИИ • DreamMatch App"
    }
};

type MediaType = 'image' | 'story_video' | null;
type SelectionStep = 'main' | 'style' | 'quality';

const DreamShare: React.FC<DreamShareProps> = ({
    dream,
    language,
    userProfile,
    onGenerateImage,
    onGenerateStoryVideo,
    tier: tierProp,
    themeMode
}) => {
    const th = getTheme(themeMode || ThemeMode.DARK);
    const t = translations[language] || translations[Language.EN];

    const [mediaType, setMediaType] = useState<MediaType>(null);
    const [selectionStep, setSelectionStep] = useState<SelectionStep>('main');
    const [selectedStyle, setSelectedStyle] = useState<'cartoon' | 'anime' | 'real' | 'fantasy' | 'surreal' | 'watercolor' | null>(null);
    const [copied, setCopied] = useState(false);

    // PDF functionality
    const [showPdfModal, setShowPdfModal] = useState(false);
    const [pdfStatus, setPdfStatus] = useState<'idle' | 'generating' | 'success'>('idle');
    const [pdfAction, setPdfAction] = useState<'download' | 'share'>('download');
    const printRef = useRef<HTMLDivElement>(null);
    const [pdfMode, setPdfMode] = useState<'papyrus' | 'mystic' | 'feminine'>('mystic');

    const tier = tierProp || userProfile?.subscriptionTier || SubscriptionTier.FREE;
    const isLocked = false; // PDF fuer alle freigeschaltet
    const hasVideoAccess = tier === SubscriptionTier.PRO || tier === SubscriptionTier.SMART;

    const shareUrl = `https://dreamcode.app/dream/${dream.id}`;
    const shareText = `Dream Code Oracle: ${dream.title}\n\n${dream.description.substring(0, 100)}...\n\n${t.web_link}`;

    // Show only 4 main styles for video, all 6 for images
    const allStyles = [
        { id: 'cartoon' as const, icon: '🎨', label: t.cartoon, desc: t.cartoon_desc, color: 'from-pink-500 to-orange-400' },
        { id: 'anime' as const, icon: '⚔️', label: t.anime, desc: t.anime_desc, color: 'from-blue-500 to-purple-500' },
        { id: 'real' as const, icon: '📷', label: t.real, desc: t.real_desc, color: 'from-gray-600 to-gray-800' },
        { id: 'fantasy' as const, icon: '✨', label: t.fantasy, desc: t.fantasy_desc, color: 'from-purple-600 to-fuchsia-600' },
        { id: 'surreal' as const, icon: '🌀', label: t.surreal, desc: t.surreal_desc, color: 'from-teal-500 to-cyan-600' },
        { id: 'watercolor' as const, icon: '🎭', label: t.watercolor, desc: t.watercolor_desc, color: 'from-rose-400 to-pink-500' }
    ];

    const styles = mediaType === 'story_video'
        ? allStyles.filter(s => ['cartoon', 'anime', 'real', 'fantasy'].includes(s.id))
        : allStyles;

    const handleMediaSelect = (type: MediaType) => {
        setMediaType(type);
        setSelectionStep('style');
    };

    const handleStyleSelect = (style: 'cartoon' | 'anime' | 'real' | 'fantasy' | 'surreal' | 'watercolor') => {
        setSelectedStyle(style);

        // Story Video doesn't need quality selection
        if (mediaType === 'story_video') {
            if (onGenerateStoryVideo) {
                onGenerateStoryVideo(style);
            }
            resetState();
        } else {
            setSelectionStep('quality');
        }
    };

    const handleQualitySelect = (quality: 'normal' | 'high') => {
        if (selectedStyle) {
            if (mediaType === 'image' && onGenerateImage) {
                onGenerateImage(quality, selectedStyle as 'cartoon' | 'anime' | 'real' | 'fantasy');
            }
        }
        resetState();
    };

    const resetState = () => {
        setMediaType(null);
        setSelectionStep('main');
        setSelectedStyle(null);
    };

    const handleBack = () => {
        if (selectionStep === 'quality') {
            setSelectionStep('style');
            setSelectedStyle(null);
        } else if (selectionStep === 'style') {
            setSelectionStep('main');
            setMediaType(null);
        }
    };

    const copyLink = () => {
        const url = `${window.location.origin}/dream/${dream.id}`;
        navigator.clipboard.writeText(url);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    // PDF functionality
    const getColors = () => {
        if (pdfMode === 'mystic') return { bg: '#05020a', text: '#e2e8f0', accent: '#a78bfa', border: 'rgba(255,255,255,0.2)' };
        if (pdfMode === 'feminine') return { bg: '#fff1f2', text: '#881337', accent: '#ec4899', border: 'rgba(236,72,153,0.3)' };
        return { bg: '#fdfbf7', text: '#1e1b4b', accent: '#5b21b6', border: 'rgba(0,0,0,0.1)' };
    };

    const colors = getColors();

    const parseInlineStyles = (text: string) => {
        const parts = text.split(/(\*\*.*?\*\*)/g);
        return parts.map((part, i) => {
            if (part.startsWith('**') && part.endsWith('**')) {
                return <strong key={i} style={{ fontWeight: 'bold', color: pdfMode === 'feminine' ? '#be185d' : 'inherit' }}>{part.slice(2, -2)}</strong>;
            }
            return part;
        });
    };

    const formatDreamText = (text: string | { interpretation: string } | any) => {
        // Handle both string and object formats
        const textStr = typeof text === 'string' ? text : (text?.interpretation || String(text));
        const lines = textStr.split('\n');
        return lines.map((line, index) => {
            const cleanLine = line.trim();
            if (!cleanLine) return <div key={index} className="h-3"></div>;

            if (cleanLine.startsWith('###')) {
                 const content = cleanLine.replace(/^###\s*/, '').replace(/\*\*/g, '');
                 return (
                     <h3 key={index} style={{
                         fontSize: '16px',
                         fontWeight: 'bold',
                         marginTop: '16px',
                         marginBottom: '6px',
                         textTransform: 'uppercase',
                         letterSpacing: '0.5px',
                         color: colors.accent,
                         borderBottom: `1px solid ${colors.border}`,
                         paddingBottom: '4px'
                     }}>
                        {content}
                     </h3>
                 );
            }

            if (cleanLine.startsWith('* ')) {
                 const content = cleanLine.replace(/^\*\s*/, '');
                 return (
                     <div key={index} style={{ display: 'flex', alignItems: 'flex-start', marginBottom: '4px', paddingLeft: '8px' }}>
                         <span style={{ marginRight: '8px', opacity: 0.7, color: colors.accent }}>•</span>
                         <span style={{ flex: 1 }}>{parseInlineStyles(content)}</span>
                     </div>
                 );
            }

            return (
                <div key={index} style={{ marginBottom: '4px', lineHeight: '1.6' }}>
                    {parseInlineStyles(cleanLine)}
                </div>
            );
        });
    };

    const handleNativeShare = async () => {
        if (navigator.share) {
            try {
                await navigator.share({
                    title: `Dream Code: ${dream.title}`,
                    text: shareText,
                    url: shareUrl,
                });
            } catch (error) {
                console.log('Error sharing:', error);
            }
        } else {
            navigator.clipboard.writeText(`${shareText} ${shareUrl}`);
            alert(t.copy_fallback);
        }
    };

    const openPdfModal = (action: 'share' | 'download') => {
        if (isLocked) {
            alert(t.locked);
            return;
        }
        setPdfAction(action);
        setShowPdfModal(true);
        setPdfStatus('idle');
    };

    const handleStartGeneration = async () => {
        setPdfStatus('generating');

        setTimeout(async () => {
            if (!printRef.current) {
                alert(t.pdf_not_ready);
                setPdfStatus('idle');
                return;
            }

            try {
                const element = printRef.current;

                const canvas = await html2canvas(element, {
                    scale: 2,
                    useCORS: true,
                    logging: false,
                    backgroundColor: colors.bg,
                    windowWidth: 800
                });

                const imgData = canvas.toDataURL('image/jpeg', 0.95);

                const imgWidthPx = canvas.width;
                const imgHeightPx = canvas.height;
                const pdfWidth = 210;
                const pdfHeight = (imgHeightPx * pdfWidth) / imgWidthPx;

                const pdf = new jsPDF('p', 'mm', [pdfWidth, pdfHeight]);

                if (pdfMode === 'mystic') {
                    pdf.setFillColor(5, 2, 10);
                } else if (pdfMode === 'feminine') {
                    pdf.setFillColor(255, 241, 242);
                } else {
                    pdf.setFillColor(253, 251, 247);
                }
                pdf.rect(0, 0, pdfWidth, pdfHeight, 'F');

                pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight);

                const footerHeight = 20;
                const linkY = pdfHeight - footerHeight;
                pdf.link(0, linkY, pdfWidth, footerHeight, { url: 'https://www.dreammatch.app' });

                const fileName = `Dream Code_${dream.date.replace(/\./g, '-')}.pdf`;

                if (pdfAction === 'share') {
                    const blob = pdf.output('blob');
                    const file = new File([blob], fileName, { type: 'application/pdf' });

                    if (navigator.canShare && navigator.canShare({ files: [file] })) {
                        try {
                            await navigator.share({
                                files: [file],
                                title: dream.title,
                                text: t.web_link
                            });
                        } catch (shareErr) {
                            console.log("Share cancelled or failed", shareErr);
                        }
                    } else {
                        pdf.save(fileName);
                    }
                } else {
                    pdf.save(fileName);
                }

                setPdfStatus('success');
                setTimeout(() => setShowPdfModal(false), 1500);

            } catch (err) {
                console.error("PDF Gen Error", err);
                setPdfStatus('idle');
                alert(t.pdf_error);
            }
        }, 500);
    };

    return (
        <div className="space-y-3">
            {/* Main Menu */}
            {selectionStep === 'main' && (
                <>
                    <div className="grid grid-cols-2 gap-2 mb-3">
                        {/* Image Generation */}
                        {onGenerateImage && (
                            <button
                                onClick={() => handleMediaSelect('image')}
                                className="py-4 px-2 bg-gradient-to-br from-purple-600 to-fuchsia-600 hover:from-purple-500 hover:to-fuchsia-500 text-white rounded-xl font-bold text-xs transition-all shadow-lg flex flex-col items-center gap-1"
                            >
                                <span className="text-2xl">🖼️</span>
                                <span>{t.generate_image}</span>
                            </button>
                        )}

                        {/* Story Video - Only for GOLD/SMART */}
                        {onGenerateStoryVideo && hasVideoAccess && (
                            <button
                                onClick={() => handleMediaSelect('story_video')}
                                className="py-4 px-2 bg-gradient-to-br from-amber-600 to-yellow-600 hover:from-amber-500 hover:to-yellow-500 text-white rounded-xl font-bold text-xs transition-all shadow-lg flex flex-col items-center gap-1 border border-amber-400/30"
                            >
                                <span className="text-2xl">🎬</span>
                                <span>{t.story_video}</span>
                                <span className="text-[10px] opacity-70">{t.story_desc}</span>
                            </button>
                        )}
                    </div>

                    {/* PDF and Share Buttons */}
                    <div className="grid grid-cols-3 gap-3">
                        <button
                            onClick={handleNativeShare}
                            className="flex flex-col items-center justify-center p-3 rounded-xl border bg-slate-800/50 border-white/10 text-slate-300 hover:bg-slate-700 hover:text-white transition-all group"
                        >
                            <span className="material-icons text-xl mb-1 group-hover:scale-110 transition-transform">share</span>
                            <span className="text-[10px] font-bold uppercase tracking-wide text-center leading-tight">{t.share_btn}</span>
                        </button>

                        <button
                            onClick={() => openPdfModal('share')}
                            className={`flex flex-col items-center justify-center p-3 rounded-xl border transition-all group relative ${isLocked ? 'bg-slate-900 border-slate-700 text-slate-500 opacity-60' : 'bg-fuchsia-900/30 border-fuchsia-500/30 text-fuchsia-200 hover:bg-fuchsia-900/50 hover:text-white'}`}
                        >
                            {isLocked && <div className="absolute top-1 right-1"><span className="material-icons text-xs text-slate-400">lock</span></div>}
                            <span className="material-icons text-xl mb-1 group-hover:scale-110 transition-transform">send_to_mobile</span>
                            <span className="text-[10px] font-bold uppercase tracking-wide text-center leading-tight">{t.pdf_share_btn}</span>
                        </button>

                        <button
                            onClick={() => openPdfModal('download')}
                            className={`flex flex-col items-center justify-center p-3 rounded-xl border transition-all group relative ${isLocked ? 'bg-slate-900 border-slate-700 text-slate-500 opacity-60' : 'bg-indigo-900/30 border-indigo-500/30 text-indigo-200 hover:bg-indigo-900/50 hover:text-white'}`}
                        >
                            {isLocked && <div className="absolute top-1 right-1"><span className="material-icons text-xs text-slate-400">lock</span></div>}
                            <span className="material-icons text-xl mb-1 group-hover:scale-110 transition-transform">download</span>
                            <span className="text-[10px] font-bold uppercase tracking-wide text-center leading-tight">{t.pdf_download_btn}</span>
                        </button>
                    </div>
                </>
            )}

            {/* Style Selection */}
            {selectionStep === 'style' && (
                <div className="space-y-3">
                    <div className="flex items-center justify-between">
                        <h4 className="text-sm font-bold text-white/80">{t.select_style}</h4>
                        <button onClick={handleBack} className="text-xs text-white/50 hover:text-white flex items-center gap-1">
                            <span className="material-icons text-sm">arrow_back</span>
                            {t.back}
                        </button>
                    </div>
                    <div className="grid grid-cols-2 gap-2">
                        {styles.map(style => (
                            <button
                                key={style.id}
                                onClick={() => handleStyleSelect(style.id)}
                                className={`py-4 px-3 bg-gradient-to-br ${style.color} hover:scale-105 border border-white/20 rounded-xl text-center transition-all shadow-lg`}
                            >
                                <span className="text-3xl block mb-1">{style.icon}</span>
                                <span className="text-sm font-bold text-white block">{style.label}</span>
                                <span className="text-[10px] text-white/70 block mt-1">{style.desc}</span>
                            </button>
                        ))}
                    </div>
                </div>
            )}

            {/* Quality Selection */}
            {selectionStep === 'quality' && (
                <div className="space-y-3">
                    <div className="flex items-center justify-between">
                        <h4 className="text-sm font-bold text-white/80">{t.select_quality}</h4>
                        <button onClick={handleBack} className="text-xs text-white/50 hover:text-white flex items-center gap-1">
                            <span className="material-icons text-sm">arrow_back</span>
                            {t.back}
                        </button>
                    </div>
                    <div className="grid grid-cols-2 gap-3">
                        <button
                            onClick={() => handleQualitySelect('normal')}
                            className="py-4 px-3 bg-gradient-to-br from-slate-700 to-slate-800 hover:from-slate-600 hover:to-slate-700 border border-white/10 rounded-xl text-center transition-all"
                        >
                            <span className="material-icons text-2xl text-white/60 mb-1">hd</span>
                            <span className="block text-sm font-bold text-white">{t.normal}</span>
                            <span className="block text-xs text-white/50 mt-1">FLUX.1</span>
                        </button>
                        <button
                            onClick={() => handleQualitySelect('high')}
                            className="py-4 px-3 bg-gradient-to-br from-amber-600 to-orange-700 hover:from-amber-500 hover:to-orange-600 border border-amber-400/30 rounded-xl text-center transition-all shadow-lg"
                        >
                            <span className="material-icons text-2xl text-amber-200 mb-1">4k</span>
                            <span className="block text-sm font-bold text-white">{t.premium}</span>
                            <span className="block text-xs text-amber-200/70 mt-1">FLUX.1 Pro</span>
                        </button>
                    </div>
                </div>
            )}

            {/* PDF Modal */}
            {showPdfModal && (
                <div className="fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4 animate-in fade-in">
                    <div className="bg-dream-deep border border-white/10 w-full max-w-md rounded-2xl p-6 shadow-2xl relative">
                        <button onClick={() => setShowPdfModal(false)} className="absolute top-3 end-3 w-11 h-11 rounded-full bg-white/5 hover:bg-white/15 flex items-center justify-center text-slate-400 hover:text-white transition-colors">
                            <span className="material-icons">close</span>
                        </button>

                        <h3 className="text-xl font-mystic text-white mb-6 text-center">{t.pdf_title}</h3>

                        <div className="grid grid-cols-3 gap-3 mb-8">
                            <button
                                onClick={() => setPdfMode('mystic')}
                                className={`p-3 rounded-xl border flex flex-col items-center gap-2 transition-all ${pdfMode === 'mystic' ? 'bg-fuchsia-900/40 border-fuchsia-500 text-white' : 'bg-black/40 border-white/10 text-slate-400'}`}
                            >
                                <div className="w-6 h-6 rounded-full bg-gradient-to-br from-indigo-900 to-black border border-white/20"></div>
                                <span className="text-[10px] font-bold">{t.style_mystic}</span>
                            </button>

                            <button
                                onClick={() => setPdfMode('papyrus')}
                                className={`p-3 rounded-xl border flex flex-col items-center gap-2 transition-all ${pdfMode === 'papyrus' ? 'bg-amber-100 border-amber-500 text-amber-900' : 'bg-amber-900/20 border-white/10 text-slate-400'}`}
                            >
                                <div className="w-6 h-6 rounded-full bg-[#fdfbf7] border border-amber-200"></div>
                                <span className="text-[10px] font-bold">{t.style_papyrus}</span>
                            </button>

                            <button
                                onClick={() => setPdfMode('feminine')}
                                className={`p-3 rounded-xl border flex flex-col items-center gap-2 transition-all ${pdfMode === 'feminine' ? 'bg-pink-100 border-pink-500 text-pink-900' : 'bg-pink-900/20 border-white/10 text-slate-400'}`}
                            >
                                <div className="w-6 h-6 rounded-full bg-[#fff1f2] border border-pink-200"></div>
                                <span className="text-[10px] font-bold">{t.style_feminine}</span>
                            </button>
                        </div>

                        <button
                            onClick={handleStartGeneration}
                            disabled={pdfStatus !== 'idle'}
                            className="w-full py-4 bg-gradient-to-r from-fuchsia-600 to-indigo-600 rounded-xl font-bold text-white shadow-lg disabled:opacity-50 flex items-center justify-center gap-2"
                        >
                            {pdfStatus === 'idle' && <><span className="material-icons">auto_fix_high</span> {t.start_btn}</>}
                            {pdfStatus === 'generating' && t.generating}
                            {pdfStatus === 'success' && <><span className="material-icons">check</span> {t.success}</>}
                        </button>
                    </div>
                </div>
            )}

            {/* Hidden PDF Template */}
            <div className="fixed top-0 left-[-9999px] z-[-50]">
                <div
                    ref={printRef}
                    style={{
                        width: '800px',
                        minHeight: '1123px',
                        height: 'auto',
                        backgroundColor: colors.bg,
                        color: colors.text,
                        fontFamily: 'serif',
                        padding: '50px',
                        display: 'flex',
                        flexDirection: 'column',
                        alignItems: 'center'
                    }}
                >
                    <div className="w-full flex justify-between items-center border-b pb-4 mb-6" style={{ borderColor: colors.border }}>
                        <h1 style={{ fontSize: '32px', fontWeight: 'bold', fontFamily: 'Cinzel, serif', color: colors.accent }}>Dream Code</h1>
                        <span style={{ fontSize: '14px', textTransform: 'uppercase', letterSpacing: '2px', opacity: 0.7 }}>{t.pdf_oracle_analysis}</span>
                    </div>

                    {dream.imageUrl && (
                        <div className="w-full mb-8 rounded-xl overflow-hidden shadow-2xl" style={{ border: `2px solid ${colors.border}` }}>
                             <img src={dream.imageUrl} alt="Dream" style={{ width: '100%', height: 'auto', display: 'block' }} />
                        </div>
                    )}

                    <div className="w-full text-center mb-8">
                        <h2 style={{ fontSize: '36px', fontWeight: 'bold', marginBottom: '10px', lineHeight: 1.2 }}>{dream.title}</h2>
                        <p style={{ fontSize: '14px', opacity: 0.7 }}>{dream.date} • {userProfile?.name || 'Dreamer'}</p>
                    </div>

                    <div className="w-full text-left" style={{ fontSize: '16px', lineHeight: '1.8' }}>
                        <div className="mb-8 p-6 rounded-xl" style={{ backgroundColor: pdfMode === 'mystic' ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.03)' }}>
                            <h3 style={{ fontSize: '12px', textTransform: 'uppercase', fontWeight: 'bold', marginBottom: '10px', opacity: 0.6 }}>{t.pdf_the_dream}</h3>
                            <p style={{ fontStyle: 'italic' }}>"{dream.description}"</p>
                        </div>

                        <div className="mb-8">
                            <h3 style={{ fontSize: '12px', textTransform: 'uppercase', fontWeight: 'bold', marginBottom: '10px', opacity: 0.6, color: colors.accent }}>{t.pdf_oracle_interpretation}</h3>
                            {formatDreamText(dream.interpretation)}
                        </div>

                        <div className="flex gap-2 flex-wrap mb-10">
                            {dream.tags.map(tag => (
                                <span key={tag} style={{
                                    padding: '4px 12px',
                                    borderRadius: '4px',
                                    fontSize: '10px',
                                    textTransform: 'uppercase',
                                    border: `1px solid ${colors.border}`,
                                    marginRight: '8px'
                                }}>
                                    {tag}
                                </span>
                            ))}
                        </div>
                    </div>

                    <div className="mt-auto w-full text-center pt-8 border-t" style={{ borderColor: colors.border }}>
                        <p style={{
                            fontSize: '18px',
                            fontWeight: 'bold',
                            color: colors.accent,
                            letterSpacing: '1px',
                            textDecoration: 'none',
                            cursor: 'pointer'
                        }}>
                            {t.web_link}
                        </p>
                        <p style={{ fontSize: '10px', opacity: 0.5, marginTop: '5px' }}>{t.pdf_generated_by}</p>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default DreamShare;
