// Auto-generated by scripts/fix-botprofiles-ocean.mjs — do not edit manually.
// Bot-IDs whose lat/lng falls outside any land polygon (world-110m).
// DreamMap filters these out of the visible marker set.
export const OCEAN_USER_IDS: Set<string> = new Set(["bot0146","bot0196","bot0198","bot0242","bot0246","bot0253","bot0358","bot0374","bot0401","bot0416","bot0425","bot0431","bot0433","bot0527","bot0580","bot0685","bot0686","bot0688","bot0696","bot0701","bot0703","bot0710","bot0729","bot0730","bot0731","bot0737","bot0738","bot0742","bot0804","bot0815","bot0818","bot0825","bot0827","bot0836","bot0863","bot0864","bot0867","bot0891"]);
