// Phase 5B: Identifiziere Bots mit lat/lng im Meer (Ocean-Fix).
// Output: data/oceanUserIds.ts (Liste von Bot-IDs die im Meer liegen — werden beim Rendern geskippt
//         ODER auf nearest Land-Centroid gesnapped, je nach Strategy).
import { booleanPointInPolygon } from '@turf/boolean-point-in-polygon';
import { point } from '@turf/helpers';
import * as fs from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const GEOJSON_PATH = join(__dirname, '..', 'public', 'world-110m.geojson');
const OUT_PATH = join(__dirname, '..', 'data', 'oceanUserIds.ts');

async function main() {
  const world = JSON.parse(fs.readFileSync(GEOJSON_PATH, 'utf8'));
  const polygons = world.features;
  console.log(`[ocean-fix] ${polygons.length} country polygons`);

  const mod = await import('../data/botProfiles.ts');
  const bots = (mod.BOT_USERS ?? mod.default ?? []);
  console.log(`[ocean-fix] checking ${bots.length} bots`);

  const oceanIds = [];
  let landHits = 0;
  for (const b of bots) {
    const pt = point([b.lng, b.lat]);
    let onLand = false;
    for (const feat of polygons) {
      try {
        if (booleanPointInPolygon(pt, feat)) { onLand = true; break; }
      } catch {}
    }
    if (onLand) landHits++;
    else oceanIds.push(b.id);
  }

  console.log(`[ocean-fix] land=${landHits} ocean=${oceanIds.length} (${(100 * oceanIds.length / bots.length).toFixed(1)}%)`);

  const out = `// Auto-generated by scripts/fix-botprofiles-ocean.mjs — do not edit manually.
// Bot-IDs whose lat/lng falls outside any land polygon (world-110m).
// DreamMap filters these out of the visible marker set.
export const OCEAN_USER_IDS: Set<string> = new Set(${JSON.stringify(oceanIds, null, 0)});
`;
  fs.writeFileSync(OUT_PATH, out);
  console.log(`[ocean-fix] DONE -- ${OUT_PATH}`);
}

main().catch(e => { console.error(e); process.exit(1); });
