// Tag inline BASE_USERS (DreamMap.tsx u1..u300) with matching symbol IDs.
// Reads BASE_USERS directly from DreamMap.tsx, matches keywords against DB catalog.
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

const ENV = fs.readFileSync(path.join(process.cwd(), '.env'), 'utf8')
  .split('\n').reduce<Record<string, string>>((acc, l) => {
    const m = l.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) acc[m[1]] = m[2].replace(/^["']|["']$/g, '');
    return acc;
  }, {});
const URL = ENV.VITE_SUPABASE_URL;
const KEY = ENV.SUPABASE_SERVICE_ROLE_KEY;
const sb = createClient(URL!, KEY!, { auth: { persistSession: false } });

const STOPWORDS = new Set(['dream','traum','like','feel','went','come','look','know','tell','thing','time','place','make','home','year','hour']);

async function fetchAll<T>(tbl: string, select: string, pageSize = 1000): Promise<T[]> {
  const out: T[] = [];
  let from = 0;
  while (true) {
    const { data, error } = await sb.from(tbl).select(select).range(from, from + pageSize - 1);
    if (error) throw error;
    if (!data || !data.length) break;
    out.push(...(data as unknown as T[]));
    if (data.length < pageSize) break;
    from += pageSize;
  }
  return out;
}

async function main() {
  const syms = await fetchAll<{ id: string; name: string }>('dream_symbols', 'id, name');
  const trans = await fetchAll<{ symbol_id: string; language_code: string; translated_name: string; aliases: string[] | null }>(
    'symbol_translations', 'symbol_id, language_code, translated_name, aliases',
  );
  const kwIdx = new Map<string, Set<string>>();
  const add = (kw: string, sid: string) => {
    const k = kw.toLowerCase().trim();
    if (!k || k.length < 4 || STOPWORDS.has(k)) return;
    if (!kwIdx.has(k)) kwIdx.set(k, new Set());
    kwIdx.get(k)!.add(sid);
  };
  for (const s of syms) add(s.name, s.id);
  for (const t of trans) {
    if (t.language_code !== 'de' && t.language_code !== 'en') continue;
    if (t.translated_name) add(t.translated_name, t.symbol_id);
    for (const a of t.aliases ?? []) if (typeof a === 'string') add(a, t.symbol_id);
  }
  const allKw = Array.from(kwIdx.keys()).sort((a, b) => b.length - a.length);
  const kwRe = new RegExp('\\b(' + allKw.map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')\\b', 'gi');
  console.log(`catalog: ${allKw.length} keywords, ${syms.length} symbols`);

  // Parse BASE_USERS out of DreamMap.tsx
  const src = fs.readFileSync(path.join(process.cwd(), 'components', 'DreamMap.tsx'), 'utf8');
  const userRe = /\{\s*id:\s*'(u\d+)'[^}]*?name:\s*'([^']+)'[^}]*?city:\s*'([^']*)'[^}]*?country:\s*'([^']*)'[^}]*?category:\s*'([^']*)'[^}]*?mood:\s*'([^']*)'[^}]*?dreamSummary:\s*'([^']+(?:\\'[^']*)*)'/g;
  const bots: Array<{ id: string; text: string }> = [];
  const matches = [...src.matchAll(userRe)];
  for (const m of matches) {
    const [, id, name, city, country, category, mood, dreamSummary] = m;
    const text = `${name} ${city} ${country} ${category} ${mood} ${dreamSummary}`;
    bots.push({ id, text });
  }
  console.log(`BASE_USERS parsed: ${bots.length}`);

  const tags: Record<string, string[]> = {};
  let total = 0, empty = 0;
  for (const b of bots) {
    const hits = new Map<string, number>();
    for (const mm of b.text.toLowerCase().matchAll(kwRe)) {
      for (const sid of kwIdx.get(mm[0])!) hits.set(sid, (hits.get(sid) ?? 0) + 1);
    }
    const sorted = Array.from(hits.entries()).sort((a, b) => b[1] - a[1]).slice(0, 20).map(x => x[0]);
    tags[b.id] = sorted;
    total += sorted.length;
    if (!sorted.length) empty++;
  }
  console.log(`tagged: ${bots.length - empty}, empty: ${empty}, avg=${(total/bots.length).toFixed(1)}`);

  const entries = bots.map(b => `  '${b.id}': ${JSON.stringify(tags[b.id] ?? [])},`).join('\n');
  const out = `// Auto-generated by scripts/tag-basemap-users.ts — do not edit manually.
// Maps BASE_USERS id (u1..uN) -> array of matching symbol IDs (DB catalog keyword match).
export const BOT_SYMBOL_IDS: Record<string, string[]> = {
${entries}
};
`;
  fs.writeFileSync(path.join(process.cwd(), 'data', 'botSymbolIds.ts'), out);
  console.log('written data/botSymbolIds.ts');
  const WASSER = '65501134-d2dc-45ea-9fda-31d4568a7af5';
  const wasserBots = Object.entries(tags).filter(([,ids]) => ids.includes(WASSER)).length;
  console.log(`bots tagged with Wasser: ${wasserBots}`);
}

main().catch(e => { console.error(e); process.exit(1); });
