// Phase-3 v2: tag every SimUser with matching symbol IDs using full DB catalog
// (symbol name + de/en translations + aliases). Deterministic, no LLM.
import { createClient } from '@supabase/supabase-js';
import * as fs from 'fs';
import * as path from 'path';

const ENV = fs.readFileSync(path.join(process.cwd(), '.env'), 'utf8')
  .split('\n').reduce<Record<string, string>>((acc, l) => {
    const m = l.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m) acc[m[1]] = m[2].replace(/^["']|["']$/g, '');
    return acc;
  }, {});
const URL = process.env.SUPABASE_URL || ENV.VITE_SUPABASE_URL;
const KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || ENV.SUPABASE_SERVICE_ROLE_KEY;
if (!URL || !KEY) { console.error('missing SUPABASE env'); process.exit(1); }
const sb = createClient(URL, KEY, { auth: { persistSession: false } });

const MIN_KW_LEN = 4;
const MAX_TAGS = 20;
const STOPWORDS = new Set([
  'dream','traum','like','feel','felt','went','come','look','know','tell',
  'thing','time','place','make','made','take','took','home','year','hour',
]);

async function fetchAll<T>(tbl: string, select: string, pageSize = 1000): Promise<T[]> {
  const out: T[] = [];
  let from = 0;
  while (true) {
    const { data, error } = await sb.from(tbl).select(select).range(from, from + pageSize - 1);
    if (error) throw error;
    if (!data || !data.length) break;
    out.push(...(data as unknown as T[]));
    if (data.length < pageSize) break;
    from += pageSize;
  }
  return out;
}

async function main() {
  const syms = await fetchAll<{ id: string; name: string }>('dream_symbols', 'id, name');
  const trans = await fetchAll<{ symbol_id: string; language_code: string; translated_name: string; aliases: string[] | null }>(
    'symbol_translations', 'symbol_id, language_code, translated_name, aliases',
  );
  const kwIdx = new Map<string, Set<string>>();
  const add = (kw: string, sid: string) => {
    const k = kw.toLowerCase().trim();
    if (!k || k.length < MIN_KW_LEN) return;
    if (STOPWORDS.has(k)) return;
    if (!kwIdx.has(k)) kwIdx.set(k, new Set());
    kwIdx.get(k)!.add(sid);
  };
  for (const s of syms) add(s.name, s.id);
  for (const t of trans) {
    if (t.language_code !== 'de' && t.language_code !== 'en') continue;
    if (t.translated_name) add(t.translated_name, t.symbol_id);
    for (const a of t.aliases ?? []) if (typeof a === 'string') add(a, t.symbol_id);
  }
  const allKw = Array.from(kwIdx.keys()).sort((a, b) => b.length - a.length);
  const kwRe = new RegExp('\\b(' + allKw.map(k => k.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')).join('|') + ')\\b', 'gi');
  console.log(`[tag-v2] keywords: ${allKw.length}, symbols: ${syms.length}`);

  const mod: any = await import('../data/botProfiles.js');
  const bots = (mod.BOT_USERS ?? mod.default ?? []) as any[];
  console.log(`[tag-v2] bots: ${bots.length}`);

  const tags: Record<string, string[]> = {};
  let totalTags = 0;
  for (const b of bots) {
    const text = `${b.dreamSummary || ''} ${b.bio || ''} ${b.category || ''} ${b.mood || ''} ${b.name || ''}`;
    const hits = new Map<string, number>();  // symbol_id -> hit count
    const low = text.toLowerCase();
    for (const m of low.matchAll(kwRe)) {
      for (const sid of kwIdx.get(m[0])!) hits.set(sid, (hits.get(sid) ?? 0) + 1);
    }
    const sorted = Array.from(hits.entries()).sort((a, b) => b[1] - a[1]).slice(0, MAX_TAGS).map(x => x[0]);
    tags[b.id] = sorted;
    totalTags += sorted.length;
  }
  const empty = bots.filter(b => !tags[b.id].length).length;
  console.log(`[tag-v2] tagged bots: ${bots.length - empty}, empty: ${empty}, avg=${(totalTags/bots.length).toFixed(1)}`);

  const entries = bots.map(b => `  '${b.id}': ${JSON.stringify(tags[b.id] ?? [])},`).join('\n');
  const out = `// Auto-generated by scripts/tag-simusers-v2.ts — do not edit manually.
// Maps bot id -> array of matching symbol IDs (DB catalog keyword match).
export const BOT_SYMBOL_IDS: Record<string, string[]> = {
${entries}
};
`;
  const outPath = path.join(process.cwd(), 'data', 'botSymbolIds.ts');
  fs.writeFileSync(outPath, out);
  console.log(`[tag-v2] written ${outPath}`);
}

main().catch(e => { console.error(e); process.exit(1); });
