// Phase 3: SimUser Symbol-Tags (Keyword-Prefilter, kein Gemini — deterministisch & schnell)
import * as fs from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CATALOG_PATH = '/tmp/symbol-catalog-local.json';
const OUT_PATH = join(__dirname, '..', 'data', 'botSymbolIds.ts');

interface Symbol { id: string; n: string; c: string | null; keywords: string[] }
const CATALOG: Symbol[] = JSON.parse(fs.readFileSync(CATALOG_PATH, 'utf8'));

function tagFromText(text: string, max = 12): string[] {
  const low = ' ' + text.toLowerCase() + ' ';
  const scored: Array<{ id: string; score: number }> = [];
  for (const s of CATALOG) {
    let hits = 0;
    for (const kw of s.keywords) {
      if (kw.length < 3) continue;
      if (low.includes(kw)) hits++;
    }
    if (hits > 0) scored.push({ id: s.id, score: hits });
  }
  scored.sort((a, b) => b.score - a.score);
  return scored.slice(0, max).map(x => x.id);
}

async function main() {
  const mod = await import('../data/botProfiles');
  const bots = ((mod as any).BOT_USERS ?? (mod as any).default ?? []) as any[];
  console.log(`[tag-simusers] ${bots.length} bots, ${CATALOG.length} symbols`);

  const tags: Record<string, string[]> = {};
  let totalTags = 0;
  for (const b of bots) {
    const text = `${b.dreamSummary || ''} ${b.bio || ''} ${b.category || ''} ${b.mood || ''}`;
    tags[b.id] = tagFromText(text);
    totalTags += tags[b.id].length;
  }

  const entries = bots.map(b => `  '${b.id}': ${JSON.stringify(tags[b.id] ?? [])},`).join('\n');
  const out = `// Auto-generated by scripts/tag-simusers.ts — do not edit manually.
// Maps bot id -> array of matching symbol IDs (keyword prefilter).
export const BOT_SYMBOL_IDS: Record<string, string[]> = {
${entries}
};
`;
  fs.writeFileSync(OUT_PATH, out);
  console.log(`[tag-simusers] DONE -- ${OUT_PATH} (${totalTags} tags, avg ${(totalTags/bots.length).toFixed(1)}/bot)`);
}

main().catch(e => { console.error(e); process.exit(1); });
